In [1]:
import numpy as np

In [2]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0, 1, 1, 0]]).T

X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    
    return 1/(1 + np.exp(-z))

In [4]:
def derivativeSig(z):
    
    return sig(z) * (1 - sig(z))

In [5]:
# One hidden layer weights

wh = 2 * np.random.random((2, 2)) - 1
bh = 2 * np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1, 1)) - 1

lr = 0.1

In [6]:
# forward propagation with 1 hidden layer

for iter in range(10000):
    
    output0 = X
    inputHidden = np.dot(output0, wh) + bh
    outputHidden = sig(inputHidden)
    inputForOutputLayer = np.dot(outputHidden, wo) + bo
    output = sig(inputForOutputLayer)

    first_term_output_layer = output - Y
    second_term_output_layer = derivativeSig(inputForOutputLayer)
    first_two_output_layer = first_term_output_layer * second_term_output_layer

    first_term_hidden_layer = np.dot(first_two_output_layer, wo.T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer * second_term_hidden_layer

    changes_output = np.dot(outputHidden.T, first_two_output_layer)
    changes_output_bias = np.sum(first_two_output_layer, axis = 0, keepdims=True)

    changes_hidden = np.dot(output0.T, first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer, axis = 0, keepdims=True)

    wo = wo - lr * changes_output
    bo = bo - lr * changes_output_bias

    wh = wh - lr * changes_hidden
    bh = bh - lr * changes_hidden_bias


output0 = X
inputHidden = np.dot(output0, wh) + bh
outputHidden = sig(inputHidden)
inputForOutputLayer = np.dot(outputHidden, wo) + bo
output = sig(inputForOutputLayer)
output, wh, bh, wo, bo

(array([[0.05721953],
        [0.94668355],
        [0.94736818],
        [0.057644  ]]),
 array([[6.11875749, 3.62291921],
        [5.88077531, 3.582995  ]]),
 array([[-2.49429386, -5.50956632]]),
 array([[ 7.5116709 ],
        [-8.24045851]]),
 array([[-3.34155021]]))